const Types = {
    PRODUCTS_DATA: 'PRODUCTS_DATA',
    FETCH_PRODUCTS_DATA: 'FETCH_PRODUCTS_DATA',
    FETCH_NEXT_PRODUCTS_DATA: 'FETCH_NEXT_PRODUCTS_DATA',
    UPDATE_PRODUCTS_DATA: 'UPDATE_PRODUCTS_DATA',
    UPDATE_NEXT_DATA_PAGE: 'UPDATE_NEXT_DATA_PAGE',
    UPDATE_AD: 'UPDATE_AD'
};

export default Types;